name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    # Install latest CMake and Ninja
    - uses: lukka/get-cmake@latest
    
    # Runs the build script in the project TLD
    # Uses Ninja for the build generator
    - name: Run build script
      run: ${{github.workspace}}/build.sh -GNinja
    
    # Runs registered unit tests with CTest
    - name: Test
      working-directory: ${{github.workspace}}/build/debug/tests
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest

